language: node_js

node_js:
  - "10"

sudo: required

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: skip

jobs:
  include:
    - stage: test
      name: "Run Tests"
      script:
        - npm run lint
        - npm run build:libs-release
        - npm test
    - stage: deploy
      name: "Deploy demo to GitHub Pages"
      if: branch = master
      script: npm run build:release
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: false
        local-dir: dist/dino-demo
        on:
          branch: master
    - &npm-publish
      stage: deploy
      name: "Build and publish @ngx-dino/core"
      if: tag IS present
      script: npm run build:lib core
      before_deploy:
        - cd dist/core
      after_deploy:
        - cd ../../
      deploy: &npm
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: cns-iu/ngx-dino
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/vega-util"
      script:
        - npm run build:lib core
        - npm run build:lib vega-util
      before_deploy:
        - cd dist/vega-util
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/datatable"
      script:
        - npm run build:lib core
        - npm run build:lib datatable
      before_deploy:
        - cd dist/datatable
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/force-network"
      script:
        - npm run build:lib core
        - npm run build:lib force-network
      before_deploy:
        - cd dist/force-network
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/geomap"
      script:
        - npm run build:lib core
        - npm run build:lib vega-util
        - npm run build:lib geomap
      before_deploy:
        - cd dist/geomap
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/scatterplot"
      script:
        - npm run build:lib core
        - npm run build:lib scatterplot
      before_deploy:
        - cd dist/scatterplot
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/science-map"
      script:
        - npm run build:lib core
        - npm run build:lib science-map
      before_deploy:
        - cd dist/science-map
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/legend"
      script:
        - npm run build:lib core
        - npm run build:lib legend
      before_deploy:
        - cd dist/legend
