language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - npm run build:release

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    local-dir: dist/dino-demo
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script:
      echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc;
      npm run publish
    on:
      tags: true
      all_branches: true
