language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g --silent "@angular/cli"

script:
  - npm run build:release

after_success:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - test $TRAVIS_TAG && npm run publish

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    local-dir: dist
    on:
      branch: master
