language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: skip

jobs:
  include:
    - stage: test
      name: "Run Tests"
      script: npm run lint
    - stage: deploy
      name: "Deploy demo to GitHub Pages"
      if: branch = master
      script: npm run build:release
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: false
        local-dir: dist/dino-demo
        on:
          branch: master
    - &npm-publish
      stage: deploy
      name: "Build and publish @ngx-dino/core"
      if: tag IS present
      script: npm run build:lib core
      before_deploy:
        - cd dist/core
      after_deploy:
        - cd ../../
      deploy: &npm
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key:
          secure: e3c4F3fC3OXvL9wN44takL+Q79QeOczn3iosCIEl8pUwoBhiSEdzc1mXjbX4n8S+ihyZ9FJf/Zusgbui+sq8OdbdZkOkxUgusK/b3sRBhi90m7Yk0349T2SEFp4D1J5HHsA3Zmby7cB6bX0OEKmUttcS+1aYmaS7oezKuD2sGpiqKkPt8T2s6N0a05j6TB5xgZKals4ykV24/L1jbLhCeKVNvNLyoJEMWA4xj98rrrsXRIn9mlVC5C3bXqsMdXk9nfxSRzzQ4wAvpy3nNT4PiQTpbrCOxFbJLOguIDMO9f0JF8hh4i+EBBE022pqf3GogbJXpqHBvMwso7yi+SrEQWGpD5yQo/RjdN5KKe+kZDbH+gkANGze2R9nC0B8Swq2gJQzB0Pmpy2Ht9aaJgXpXXB7VnMeEGh4+C6hqLth2p3v/yO8gKfvD3XdCWP7APc/NOlBnb8bUrds//j0ag6Hi8l9D2IZ4aT6jjh0Zm/kwfdj2i+oqAsmVVmxMeZFBtamRlZxmBeZl2jgXyWblP8OptvdjAwumpbDNBF+4j9m7so24Q2gCjuej6kDMgukwgoKYM/GwvbI0rlH0NbdRCvaVa/+Z+ueVEMCcsUG17qO5BbJmLaDNTDyQBrExz/HnTRSkmOfnCOEw00f1/7XtuFWHzjZFXJO+zjNXOeruM6FOlE=
        on:
          tags: true
          repo: cns-iu/ngx-dino
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/vega-util"
      script:
        - npm run build:lib core
        - npm run build:lib vega-util
      before_deploy:
        - cd dist/vega-util
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/datatable"
      script:
        - npm run build:lib core
        - npm run build:lib datatable
      before_deploy:
        - cd dist/datatable
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/force-network"
      script:
        - npm run build:lib core
        - npm run build:lib force-network
      before_deploy:
        - cd dist/force-network
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/geomap"
      script:
        - npm run build:lib core
        - npm run build:lib vega-util
        - npm run build:lib geomap
      before_deploy:
        - cd dist/geomap
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/scatterplot"
      script:
        - npm run build:lib core
        - npm run build:lib scatterplot
      before_deploy:
        - cd dist/scatterplot
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/science-map"
      script:
        - npm run build:lib core
        - npm run build:lib science-map
      before_deploy:
        - cd dist/science-map
    - <<: *npm-publish
      name: "Build and publish @ngx-dino/legend"
      script:
        - npm run build:lib core
        - npm run build:lib legend
      before_deploy:
        - cd dist/legend
