language: node_js

node_js:
  - "9"
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g "@angular/cli"

script:
  - npm ci
  - npm run build-release

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    local-dir: dist
    on:
      branch: master

  - provider: npm
      email: $NPM_USER
      api_key: $NPM_TOKEN
      on:
        tags: true
        repo: cns-iu/ngx-dino
